/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// TapData Documentation docs list
  TapData: [
  'what-is-tapdata',
    {
     type: 'category',
     label: 'Introduction',
     link: {type: 'doc', id: 'introduction/README'},
     items: [
             'introduction/architecture',
             'introduction/features',
             'introduction/use-cases',
             'introduction/compare-editions',
             'introduction/change-data-capture-mechanism',
             'introduction/security',
             'introduction/tapdata-vs-kafka',
             'introduction/tapdata-vs-informatica',
             'introduction/performance',
             'introduction/terms',
       ]
    },
    {
     type: 'category',
     label: 'Getting Started',
     link: {type: 'doc', id: 'getting-started/README'},
     items: [
            {
            type: 'category',
            label: 'Step 1: Install and Setup',
            link: {type: 'doc', id: 'getting-started/install-and-setup/README'},
            items: [
                     'getting-started/install-and-setup/install-enterprise-edition',
                     'getting-started/install-and-setup/install-community-edition',
                     ]
            },
            'getting-started/connect-data-source',
            'getting-started/build-real-time-materialized-view',
            'getting-started/publish-imv-as-api',
     ]
    },
    {
         type: 'category',
         label: 'Connect Data Sources',
         link: {type: 'doc', id: 'connectors/README'},
         items: [
                 'connectors/supported-data-sources',
                 {
                  type: 'category',
                  label: 'Warehouses and Lakes',
                  link: {type: 'doc', id: 'connectors/warehouses-and-lake/README'},
                  items: [
                          'connectors/warehouses-and-lake/big-query',
                          'connectors/warehouses-and-lake/clickhouse',
                          'connectors/warehouses-and-lake/databend',
                          'connectors/warehouses-and-lake/doris',
                          'connectors/warehouses-and-lake/gaussdb',
                          'connectors/warehouses-and-lake/greenplum',
                          'connectors/warehouses-and-lake/hudi',
                          'connectors/warehouses-and-lake/selectdb',
                          'connectors/warehouses-and-lake/starrocks',
                          'connectors/warehouses-and-lake/tablestore',
                          'connectors/warehouses-and-lake/yashandb',
                         ]
                  },
                 {
                  type: 'category',
                  label: 'On-Prem Databases',
                  link: {type: 'doc', id: 'connectors/on-prem-databases/README'},
                  items: [
                          'connectors/on-prem-databases/dameng',
                          'connectors/on-prem-databases/db2',
                          'connectors/on-prem-databases/elasticsearch',
                          'connectors/on-prem-databases/gbase-8a',
                          'connectors/on-prem-databases/gbase-8s',
                          'connectors/on-prem-databases/hive1',
                          'connectors/on-prem-databases/hive3',
                          'connectors/on-prem-databases/informix',
                          'connectors/on-prem-databases/kingbase-es-r3',
                          'connectors/on-prem-databases/kingbase-es-r6',
                          'connectors/on-prem-databases/mariadb',
                          'connectors/on-prem-databases/mongodb',
                          'connectors/on-prem-databases/mongodb-below34',
                          'connectors/on-prem-databases/mrs-hive3',
                          'connectors/on-prem-databases/mysql',
                          'connectors/on-prem-databases/mysql-pxc',
                          'connectors/on-prem-databases/oceanbase',
                          'connectors/on-prem-databases/oceanbase-oracle',
                          'connectors/on-prem-databases/opengauss',
                          'connectors/on-prem-databases/oracle',
                          'connectors/on-prem-databases/postgresql',
                          'connectors/on-prem-databases/redis',
                          'connectors/on-prem-databases/sqlserver',
                          'connectors/on-prem-databases/sybase',
                          'connectors/on-prem-databases/tdengine',
                          'connectors/on-prem-databases/tidb',
                          'connectors/on-prem-databases/vastbase',
                          ]
                  },
                  {
                   type: 'category',
                   label: 'Cloud Databases',
                   link: {type: 'doc', id: 'connectors/cloud-databases/README'},
                   items: [
                           'connectors/cloud-databases/aliyun-adb-mysql',
                           'connectors/cloud-databases/aliyun-adb-postgresql',
                           'connectors/cloud-databases/aliyun-mongodb',
                           'connectors/cloud-databases/aliyun-rds-for-mariadb',
                           'connectors/cloud-databases/aliyun-rds-for-mongodb',
                           'connectors/cloud-databases/aliyun-rds-for-mysql',
                           'connectors/cloud-databases/aliyun-rds-for-pg',
                           'connectors/cloud-databases/aliyun-rds-for-sql-server',
                           'connectors/cloud-databases/amazon-rds-mysql',
                           'connectors/cloud-databases/huawei-cloud-gaussdb',
                           'connectors/cloud-databases/mongodb-atlas',
                           'connectors/cloud-databases/polardb-mysql',
                           'connectors/cloud-databases/polardb-postgresql',
                           'connectors/cloud-databases/tencentdb-for-mariadb',
                           'connectors/cloud-databases/tencentdb-for-mongodb',
                           'connectors/cloud-databases/tencentdb-for-mysql',
                           'connectors/cloud-databases/tencentdb-for-pg',
                           'connectors/cloud-databases/tencentdb-for-sql-server',
                          ]
                   },
                  {
                   type: 'category',
                   label: 'MQ and Middleware',
                   link: {type: 'doc', id: 'connectors/mq-and-middleware/README'},
                   items: [
                           'connectors/mq-and-middleware/activemq',
                           'connectors/mq-and-middleware/ai-chat',
                           'connectors/mq-and-middleware/bes-channels',
                           'connectors/mq-and-middleware/hazelcast-cloud',
                           'connectors/mq-and-middleware/kafka-enhanced',
                           'connectors/mq-and-middleware/kafka',
                           'connectors/mq-and-middleware/rabbitmq',
                           'connectors/mq-and-middleware/rocketmq',
                          ]
                   },
                   {
                   type: 'category',
                   label: 'CRM and Sales Analytics',
                   link: {type: 'doc', id: 'connectors/crm-and-sales-analytics/README'},
                   items: [
                           'connectors/crm-and-sales-analytics/hubspot',
                           'connectors/crm-and-sales-analytics/metabase',
                           'connectors/crm-and-sales-analytics/salesforce',
                           'connectors/crm-and-sales-analytics/zoho-crm',
                          ]
                   },
                   {
                    type: 'category',
                    label: 'SaaS and APIs',
                    link: {type: 'doc', id: 'connectors/saas-and-api/README'},
                    items: [
                            'connectors/saas-and-api/coding',
                            'connectors/saas-and-api/feishu-bitable',
                            'connectors/saas-and-api/github',
                            'connectors/saas-and-api/lark-approval',
                            'connectors/saas-and-api/lark-doc',
                            'connectors/saas-and-api/lark-im',
                            'connectors/saas-and-api/lark-task',
                            'connectors/saas-and-api/quick-api',
                            'connectors/saas-and-api/vika',
                            'connectors/saas-and-api/zoho-desk',
                           ]
                   },
                   {
                    type: 'category',
                    label: 'E-Commerce',
                    link: {type: 'doc', id: 'connectors/e-commerce/README'},
                    items: [
                            'connectors/e-commerce/alibaba-1688',
                            'connectors/e-commerce/shein',
                           ]
                   },
                   {
                    type: 'category',
                    label: 'Files',
                    link: {type: 'doc', id: 'connectors/files/README'},
                    items: [
                            'connectors/files/csv',
                            'connectors/files/excel',
                            'connectors/files/json',
                            'connectors/files/xml',
                           ]
                   },
                   {
                    type: 'category',
                    label: 'Others',
                    link: {type: 'doc', id: 'connectors/others/README'},
                    items: [
                            'connectors/others/custom-connection',
                            'connectors/others/dummy',
                            'connectors/others/http-receiver',
                            'connectors/others/mock-source',
                            'connectors/others/mock-target',
                           ]
                   },
                   'connectors/manage-connection',
                   'connectors/pre-check',
                   'connectors/trouble-shooting-connection',
         ]
    },
    {
      type: 'category',
      label: 'Operational Data Hub',
      link: { type: 'doc', id: 'operational-data-hub/README' },
      items: [
        'operational-data-hub/plan-data-platform',
        'operational-data-hub/set-up-odh',
        {
          type: 'category',
          label: 'Ingest and Sync Data (FDM Layer)',
          link: { type: 'doc', id: 'operational-data-hub/fdm-layer/README' },
          items: [
            'operational-data-hub/fdm-layer/replicate-data',
            'operational-data-hub/fdm-layer/validate-data-quality',
            'operational-data-hub/fdm-layer/explore-fdm-tables'
          ],
        },
        {
          type: 'category',
          label: 'Design and Transform Data (MDM Layer)',
          link: { type: 'doc', id: 'operational-data-hub/mdm-layer/README' },
          items: [
            'operational-data-hub/mdm-layer/define-data-categories',
            'operational-data-hub/mdm-layer/prepare-and-transform',
            'operational-data-hub/mdm-layer/process-node',
            'operational-data-hub/mdm-layer/build-view-in-odh'
          ],
        },
        {
          type: 'category',
          label: 'Deliver Data (ADM Layer)',
          link: { type: 'doc', id: 'operational-data-hub/adm-layer/README' },
          items: [
            'operational-data-hub/adm-layer/integrate-apis',
            'operational-data-hub/adm-layer/sync-downstream'
          ],
        },
        {
          type: 'category',
          label: 'Advanced Features & Extensions',
          link: { type: 'doc', id: 'operational-data-hub/advanced/README' },
          items: [
            'operational-data-hub/advanced/custom-node',
            'operational-data-hub/advanced/manage-external-storage',
            'operational-data-hub/advanced/manage-function',
            'operational-data-hub/advanced/share-cache',
            'operational-data-hub/advanced/share-mining'
          ],
        },
      ],
    },
    {
     type: 'category',
     label: 'Data Replication',
     link: {type: 'doc', id: 'data-replication/README'},
     items: [
            'data-replication/create-task',
            'data-replication/incremental-check',
            'data-replication/manage-task',
            'data-replication/monitor-task'
            ]
     },    
    {
      type: 'category',
      label: 'Design Incremental Materialized Views',
      link: { type: 'doc', id: 'design-incremental-views/README' },
      items: [
        'design-incremental-views/overview',
        {
          type: 'category',
          label: 'Create Views',
          link: { type: 'doc', id: 'design-incremental-views/create-views/README' },
          items: [
            'design-incremental-views/create-views/using-imv-guide',
            'design-incremental-views/create-views/using-data-pipeline-ui',
            'design-incremental-views/create-views/using-tapflow',
          ],
        },
        /*'design-incremental-views/design-considerations',*/
        'design-incremental-views/monitor-view-tasks',
        'design-incremental-views/manage-task',
      ],
    },
    {
      type: 'category',
      label: 'Publish Data as APIs ',
      link: {type: 'doc', id: 'publish-apis/README'},
      items:[
             'publish-apis/manage-app',
             'publish-apis/create-api-service',
             'publish-apis/create-api-client',
             'publish-apis/create-api-server',
             'publish-apis/manage-api-versions',
             'publish-apis/audit-api',
             'publish-apis/monitor-api-request',
             'publish-apis/api-auth',
             'publish-apis/query-via-restful',
             'publish-apis/query-via-graphql',
             'publish-apis/api-query-params',
             ]
    },
    {
     type: 'category',
     label: 'Chat with Data via MCP',
     link: {type: 'doc', id: 'mcp/README'},
     items: [
            'mcp/introduction',
            'mcp/quick-start'
            ]
     },
    {
     type: 'category',
     label: 'TapFlow Developer Guide',
     link: {type: 'doc', id: 'tapflow/README'},
     items: [
            'tapflow/introduction',
            'tapflow/quick-start',
            {
             type: 'category',
             label: 'TapFlow API Reference',
             link: {type: 'doc', id: 'tapflow/api-reference/README'},
             items: [
                    'tapflow/api-reference/data-source',
                    'tapflow/api-reference/data-flow',
             ]
            },
            'tapflow/tapshell-reference',
            {
             type: 'category',
             label: 'Typical Use Cases',
             link: {type: 'doc', id: 'tapflow/tapflow-tutorial/README'},
             items: [
                    'tapflow/tapflow-tutorial/build-real-time-wide-table',
                    'tapflow/tapflow-tutorial/expand-mogodb-array-to-mysql',
                    'tapflow/tapflow-tutorial/merge-inventory-to-mongodb',
             ]
            },
            ]
    },
    {
      type: 'category',
      label: 'System Admin ',
      link: {type: 'doc', id: 'system-admin/README'},
      items:[
             'system-admin/manage-user',
             'system-admin/manage-role',
             'system-admin/manage-cluster',
             'system-admin/operation-log',
            {
              type: 'category',
              label: 'Other Settings',
              link: {type: 'doc', id: 'system-admin/other-settings/README'},
              items:[
                     'system-admin/other-settings/system-settings',
                     'system-admin/other-settings/notification',
                     'system-admin/other-settings/manage-license',
                     'system-admin/other-settings/check-version',
                    ]
            },
            ]
    },
    {
     type: 'category',
     label: 'Platform Operations',
     link: {type: 'doc', id: 'platform-ops/README'},
     items: [
            {
              type: 'category',
              label: 'Production Deployment',
              link: {type: 'doc', id: 'platform-ops/production-deploy/README'},
              items:[
                     'platform-ops/production-deploy/capacity-planning',
                     'platform-ops/production-deploy/install-tapdata-ha',
                     'platform-ops/production-deploy/install-tapdata-ha-with-3-node',
                     'platform-ops/production-deploy/install-replica-mongodb',
                    ]
             },
            'platform-ops/operation',
            {
              type: 'category',
              label: 'Troubleshooting',
              link: {type: 'doc', id: 'platform-ops/troubleshooting/README'},
              items: [
                     'platform-ops/troubleshooting/error-code',
                     'platform-ops/troubleshooting/error-and-solutions',
                     ]
            },
            'platform-ops/emergency-plan',
        ]
    },
    {
     type: 'category',
     label: 'Practical Cases',
     link: {type: 'doc', id: 'case-practices/README'},
     items: [
             {
            type: 'category',
            label: 'Data Pipeline Cases',
            link: {type: 'doc', id: 'case-practices/pipeline-tutorial/README'},
            items: [
                    'case-practices/pipeline-tutorial/mysql-bi-directional-sync',
                    'case-practices/pipeline-tutorial/excel-to-mysql',
                    'case-practices/pipeline-tutorial/mysql-to-aliyun',
                    'case-practices/pipeline-tutorial/mysql-to-bigquery',
                    'case-practices/pipeline-tutorial/mysql-to-redis',
                    'case-practices/pipeline-tutorial/oracle-to-kafka',
                    'case-practices/pipeline-tutorial/oracle-to-tablestore',
                    'case-practices/pipeline-tutorial/extract-array',
                    ]
            },
            {
             type: 'category',
             label: 'Best Practices',
             link: {type: 'doc', id: 'case-practices/best-practice/README'},
             items: [
                'case-practices/best-practice/data-sync',
                'case-practices/best-practice/handle-schema-changes',
                'case-practices/best-practice/heart-beat-task',
                'case-practices/best-practice/alert-via-qqmail',
                'case-practices/best-practice/full-breakpoint-resumption',
                'case-practices/best-practice/raw-logs-solution',
            ]
        },
        ]
    },
    {
     type: 'category',
     label: 'FAQs',
     link: {type: 'doc', id: 'faq/README'},
     items: [
            'faq/use-product',
            'faq/data-pipeline',
            'faq/agent-installation',
            'faq/data-security',
            'faq/no-supported-data-type',
            'faq/error-code-solution',
        ]
    },
    {
     type: 'category',
     label: 'Reference',
     link: {type: 'doc', id: 'appendix/README'},
     items: [
            'appendix/standard-js',
            'appendix/enhanced-js',
            'appendix/benchmark',
            'appendix/support'
        ]
    },
    'release-notes-on-prem',
    /*{
     type: 'category',
     label: 'Release Notes',
     link: {type: 'doc', id: 'release-notes/README'},
     items: [
            'release-notes/release-notes-cloud',
            'release-notes/release-notes-on-prem',
            'release-notes/release-notes-community'
        ]
    },
    {
     type: 'category',
     label: 'User Guide',
     link: {type: 'doc', id: 'user-guide/README'},
     items: [
             'user-guide/log-in',
             'user-guide/workshop',
             'user-guide/manage-agent',
             'user-guide/manage-connection',
             {
              type: 'category',
              label: 'Real-time Data Hub',
              link: {type: 'doc', id: 'user-guide/real-time-data-hub/README'},
              items:[
                    {
                     type: 'category',
                     label: 'Data Integration Mode',
                     link: {type: 'doc', id: 'user-guide/real-time-data-hub/etl-mode/README'},
                     items:[
                            'user-guide/real-time-data-hub/etl-mode/etl-mode-dashboard',
                            'user-guide/real-time-data-hub/etl-mode/create-etl-task',
                           ]
                    },
                    {
                     type: 'category',
                     label: 'Data as Sevice Mode',
                     link: {type: 'doc', id: 'user-guide/real-time-data-hub/daas-mode/README'},
                     items:[
                            'user-guide/real-time-data-hub/daas-mode/enable-daas-mode',
                            'user-guide/real-time-data-hub/daas-mode/daas-mode-dashboard',
                            'user-guide/real-time-data-hub/daas-mode/create-daas-task',
                           ]
                    },
                    ]
             },
             {
              type: 'category',
              label: 'Data Replication',
              link: {type: 'doc', id: 'user-guide/copy-data/README'},
              items:[
                     'user-guide/copy-data/create-task',
                     'user-guide/copy-data/quick-create-task',
                     'user-guide/copy-data/manage-task',
                     'user-guide/copy-data/process-node',
                     'user-guide/copy-data/monitor-task',
                    ]
              },
              {
               type: 'category',
               label: 'Data Transformation',
               link: {type: 'doc', id: 'user-guide/data-development/README'},
               items:[
                      'user-guide/data-development/create-task',
                      'user-guide/data-development/create-materialized-view',
                      'user-guide/data-development/manage-task',
                      'user-guide/data-development/process-node',
                      'user-guide/data-development/monitor-task',
                     ]
               },
             'user-guide/incremental-check',
             'user-guide/pre-check',
             {
              type: 'category',
              label: 'Advanced Settings',
              link: {type: 'doc', id: 'user-guide/advanced-settings/README'},
              items:[
                     'user-guide/advanced-settings/share-cache',
                     'user-guide/advanced-settings/manage-function',
                     'user-guide/advanced-settings/custom-node',
                     'user-guide/advanced-settings/share-mining',
                     'user-guide/advanced-settings/manage-external-storage',
                    ]
             },

    {
     type: 'category',
     label: 'MCP Server Guide (Preview)',
     link: {type: 'doc', id: 'mcp/README'},
     items: [
            'mcp/introduction',
            'mcp/quick-start',
            ]
     },
    */
 ]
};

module.exports = sidebars;
